name: Free RDP

on: workflow_dispatch

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Download ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath .
          
      - name: Setup ngrok token
        run: ./ngrok.exe config add-authtoken 2b0vAGiKPXU6m5u71GQm1gTTtzr_5tjtXQfiNtevwrafEcUMV
        
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString "P@ssw0rd123!" -AsPlainText -Force)
          
      - name: Start tunnel
        run: ./ngrok.exe tcp 3389
